### ISSUE TITLE
Сборка из sdk

### ISSUE THREAD

**Issue by TimurDD** [samoilovv/TinkoffInvestSDK#14]
Несколько дней бьюсь, уже не знаю что спрашивать у поисковика, чтобы заработало(
Выполнил сборку, открыл через VS Studio TinkoffInvestSDK.sln и проинсталлировал (решение INSTALL, собрать).
Создал пустой проект в VS Studio, кинул в папку sdk все файлы из папки services (в т.ч. investapiclient) и файлы *.cc, *.h из папки build.
При попытке собрать пишет такие ошибки:
error C4996: 'tinkoff::public_::invest::api::contract::v1::TradeInstrument::set_figi': объявлен deprecate (не проверял, но такое ощущение, что на все методы такое пишет tinkoff::public_::invest::api::contract::v1)

warning C4273: MarketDataStream::SubscribeCandlesAsync: несовместимое связывание dll

**Comment by samoilovv** [comment]
Здравствуйте. 
В файле CMakeLists.txt написан скрипт настройки сборки проекта со скачиванием всех зависимостей, Visual Studio поддерживает CMake проекты, попробуйте открыть CMakeLists.txt через студию и сконфигурировать проект.

И собирается ли проект через командную строку, как в описании?  

Ошибка

>  error C4996: 'tinkoff::public_::invest::api::contract::v1::TradeInstrument::set_figi': объявлен deprecate

 не является критической. Возможно где-то в Visual Studio нужно снять соответствующую галочку.

**Comment by TimurDD** [comment]
Проект Ваш собирается, все ок. Но в своем ничего не работает(
У меня не так много опыта в ++, потому могу глупые вопросы задавать.
Собрал проект, взял все файлы (писал выше), сложил в папку sdk, кинул к себе в проект.
Сейчас при сборке такие ошибки
![image](https://github.com/samoilovv/TinkoffInvestSDK/assets/109646994/119e565b-2c1d-41fe-a2a2-bc05b0f0a9ef)

**Comment by samoilovv** [comment]
Это ошибки линковщика. Где-то в настройках нужно правильные пути прописать к библиотеке SDK. Я сам студией не пользуюсь, делаю все через CMake. Вот здесь пример телеграм-бота с подключением и использованием SDK https://github.com/samoilovv/TinkoffInvestBot . Такой пример не поможет?

**Comment by TimurDD** [comment]
Легче не стало. А можно без cmake использовать sdk? Я, пока что, с cmake на вы.

**Comment by samoilovv** [comment]
> Легче не стало. А можно без cmake использовать sdk? Я, пока что, с cmake на вы.

Вам нужно подключить SDK как обычную динамическую библиотеку dll с ранним связыванием. Посмотрите примеры, как это делается в Visual Studio  

Или соберите dll из моего проекта и подключите ее к своему проекту как динамическую библиотеку с поздним связыванием.

**Comment by TimurDD** [comment]
Спасибо, попробую.

**Comment by Roy2player** [comment]
Думаю "просто" подключить СДК как библиотеку не получится. Проще будет собирать ваш собственный проект через cmake, взяв за основу конфигурационный файл СДК.

**Comment by TimurDD** [comment]
@Roy2player получается, проблемы у меня из-за не знания cmake. С этим знанием (как и чего), по идее, проблем быть не должно? Все должно летать?

**Comment by Roy2player** [comment]
Заставить это работать можно разными путями. Как по мне - самый простой, это внедрить в cmake config сборку файлов вашего проекта. К тому же, знание cmake это куда более полезная вещь, чем знание vscode/vs ИМХО.

Да, если вы узнаете как это сделать и сделаете, ваш проект успешно скомпилируется 🙂

**Comment by TimurDD** [comment]
Помогите, не могу разобраться. В проекте корневая папка с cmakelists.txt, tinkoffsd и мой код (в папке). В cmakelists.txt следующее:
`target_link_libraries(${PROJECT_NAME}
    PUBLIC
    tink_grpc_proto
    TinkoffInvestSDK
    )

target_include_directories(${PROJECT_NAME}
    PUBLIC
        ${CMAKE_CURRENT_BINARY_DIR}
        ${CMAKE_CURRENT_SOURCE_DIR}
    )

include_directories(${CMAKE_SOURCE_DIR}/TinkoffInvestSDK)
include_directories(${CMAKE_SOURCE_DIR}/TinkoffInvestSDK/services)`

Сборка проходит норм, при запуске приложения пишет, что библиотека TinkoffInvestSDK не найдена(

Если руками в Debug кинуть библиотеку, то работает.

**Comment by samoilovv** [comment]
> Если руками в Debug кинуть библиотеку, то работает.

Не понятно, какая у вас структура проекта. Но скорее всего, можно в cmake прописать команду COPY, которая скопирует нужные библиотеки в нужные папки

**Comment by TimurDD** [comment]
Я делал по аналогии с вашим ботом (телеграмма). В корне только файл cmakelists.txt:
`cmake_minimum_required (VERSION 3.8)

if (POLICY CMP0141)
  cmake_policy(SET CMP0141 NEW)
  set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "$<IF:$<AND:$<C_COMPILER_ID:MSVC>,$<CXX_COMPILER_ID:MSVC>>,$<$<CONFIG:Debug,RelWithDebInfo>:EditAndContinue>,$<$<CONFIG:Debug,RelWithDebInfo>:ProgramDatabase>>")
endif()

project ("Tinkoff")

add_subdirectory ("TinkoffInvestSDK")
add_subdirectory ("TinkoffAPI")`

В папке TinkoffAPI cmakelists.txt:
`project(TinkoffAPI)

add_executable(${PROJECT_NAME} "TinkoffAPI.cpp" "TinkoffAPI.h")

if (CMAKE_VERSION VERSION_GREATER 3.12)
  set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 20)
endif()

target_link_libraries(${PROJECT_NAME}
    PUBLIC
    tink_grpc_proto
    TinkoffInvestSDK
    )

target_include_directories(${PROJECT_NAME}
    PUBLIC
        ${CMAKE_CURRENT_BINARY_DIR}
        ${CMAKE_CURRENT_SOURCE_DIR}
    )

include_directories(${CMAKE_SOURCE_DIR}/TinkoffInvestSDK)
include_directories(${CMAKE_SOURCE_DIR}/TinkoffInvestSDK/services)`

В сети все облазил, вроде все правильно делаю, подключаю вашу sdk через target_link_libraries, но не работает.
Более того, сама dll то генерится, почему ее не видит...

**Comment by TimurDD** [comment]
Получилось запустить, поправив в cmakelists.txt 
add_library(${PROJECT_NAME} SHARED ${TARGET_SRC} ${TARGET_HDR})
убрав SHARED.
