### ISSUE TITLE
Версия API

### ISSUE THREAD

**Issue by RFOmega** [samoilovv/TinkoffInvestSDK#4]
Здравствуйте. не нашел в описании какую версию API вы используете в своем SDK?

**Comment by samoilovv** [comment]
Здравствуйте. Используется новая версия API, которая основана на протоколе gRPС. Ссылка на API есть в самом репозитории https://github.com/Tinkoff/investAPI

**Comment by RFOmega** [comment]
Спасибо, можно указать эту информацию в описании, во избежание смежных вопросов в будущем. Я пару недель назад пытался отправаить коммит, затрагивающий обработку ошибок со стримов, но он был заблокирован.

**Comment by samoilovv** [comment]
Коммит в этот репозиторий? Попробуйте отправить через pull request, я коммит не видел и не блокировал.
